language: node_js
node_js:
  - "4"
  - "5"
  - "6"
os:
  - linux
sudo: false
before_script:
  - sh -c "git log | head -12"
script:
  - npm run coverage
after_success:
  - coveralls < ./coverage/lcov.info
  - CODECLIMATE_REPO_TOKEN=fb038884df12a473bb3cc13c8ef5323227e19c8818327926cde26e89eb7f31cb codeclimate-test-reporter < ./coverage/lcov.info
